### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by c0b41** [matteocontrini/node-periscope-recorder#1]
live stream && last brodcast not download.
ffmpeg exited 1, I think necessary cookies

**Comment by a1ex7** [comment]
live stream working
broadcast downloading by **replay_url** not working - _access denied_ and VLC also not playing this url

**Comment by Iragne** [comment]
Header issue .... add the cloudfront access token and other into the header of your request.

**Comment by a1ex7** [comment]
How to add header to ffmpeg in this part code
`ffmpeg(hls).on('error', function(err) { console.log(err.message) })    .output(userId + '-' + Math.round(Date.now() / 1000) + '.mp4').run();`
because ffmpeg access denied in other case
`'-header'` option not worked

**Comment by matteocontrini** [comment]
@a1ex7 what header key/value pair have you tried to send?

**Comment by a1ex7** [comment]
I tried to send cookies header: CloudFront-Policy, CloudFront-Signature and CloudFront-Key-Pair-Id

For this I used `ffmpeg(replay_url).addOption('-headers', 'Cookie:....')...` but 403 error

May be something wrong. I don't now node.js
